-- 코드를 입력하세요
-- 2021년 가입 
-- 상품 구매 회원수 / 가입 회원 수 => 두번째자리에서 반올림
-- 연 오름차순, 월 오름차순

SELECT YEAR, MONTH, COUNT(*) AS PUCHASED_USERS, 
ROUND((COUNT(*) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)), 1) AS PUCHASED_RATIO
FROM (
    SELECT DISTINCT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.USER_ID
    FROM ONLINE_SALE S
    JOIN USER_INFO U ON S.USER_ID = U.USER_ID AND YEAR(JOINED) = 2021
) A
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH