-- 코드를 입력하세요
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN (
    SELECT *
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'fruit_based'
) B ON A.FLAVOR = B.FLAVOR
WHERE TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;