-- 코드를 입력하세요
-- 중고 거래 게시물 3건 이상 등록
-- 주소는 시, 도로명 주소, 상세주소 같이
-- 전화번호 - 삽입 출력
SELECT DISTINCT(A.USER_ID), A.NICKNAME, 
CONCAT(A.CITY," ", A.STREET_ADDRESS1, " ", A.STREET_ADDRESS2) AS 전체주소, 
CONCAT(LEFT(A.TLNO,3),"-",MID(A.TLNO,4,4),"-",RIGHT(A.TLNO,4)) AS 전화번호
FROM USED_GOODS_USER AS A
JOIN USED_GOODS_BOARD AS B ON A.USER_ID = B.WRITER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY USER_ID DESC