# 2022년 1월 도서 판매 데이터
# 저자별, 카테고리 별 매출액
# 저자 ID, 저자명, 카테고리,매출액
# 저자 ID 오름, 카테고리 내림

SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((PRICE*SALES)) AS TOTAL_SALES
FROM BOOK_SALES AS S
JOIN BOOK AS B ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, CATEGORY DESC